### ISSUE TITLE
Support base64

### ISSUE THREAD

**Issue by pi0** [unjs/undio#6]

**Comment by pi0** [comment]
@itpropro Would you like to help on this? I think now finally found best home for https://github.com/unjs/knitwork/pull/83 🙈

**Comment by itpropro** [comment]
Hey,
no problem, I can move the knitwork implementation here. I have also a alternative suggestion, which is relying on the 0 deps [scure-base ](https://github.com/paulmillr/scure-base), which I could implement a wrapper for in undio. The reasoning would be that that library is independently audited and thereby usable for crypto relevant use cases without worrying about unhandled edge cases. It also works cross platform/runtime.
What do you think @pi0, it’s a similar situation to the uncrypto AES-GCM-SIV one. I am fine with both ways, whatever you prefer :)

**Comment by pi0** [comment]
I think the main goal here is simple base64 data io conversation which is a common encoding.

**Comment by pi0** [comment]
#8
